services:
  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin/phpmyadmin # Cambiado a la imagen estándar
  #   restart: always
  #   environment:
  #     PMA_ABSOLUTE_URI: https://timbre.inspedralbes.cat/pma/
  #   ports:
  #     - 9090:80
  #   depends_on:
  #     - db

  node:
    container_name: lethalrun_node
    image: node:22.13.0-bullseye-slim
    restart: always
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run start"
    # depends_on:
    #   - db


  # nuxt:
  #   container_name: soundoclock_nuxt
  #   image: node:20.11.1-bullseye-slim
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./nuxt:/usr/src/app
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - WATCHPACK_POLLING=true
  #     - CHOKIDAR_USEPOLLING=true
  #   tmpfs:
  #     - /tmp
  #   command: sh -c "node ./server/index.mjs -- --host=http://timbre.inspedralbes.cat:8080"


