name: Deploy to Clouding VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Clouding VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.CLOUDING_HOST }}
          username: ${{ secrets.CLOUDING_USER }}
          key: ${{ secrets.CLOUDING_SSH_KEY }}
          script: |
            set -e  # Detener el script si hay errores

            # Ir a la carpeta del servidor
            cd /var/www/lethalrun

            # Limpiar despliegues anteriores
            rm -rf temp_deploy temp_nuxt
            mkdir temp_deploy temp_nuxt

            # Clonar el repositorio público (sin autenticación)
            git clone --depth=1 https://github.com/inspedralbes/prj-final-front-back-g3_lethalrun.git temp_deploy

            # Copiar backend a la ubicación correcta
            rsync -av --delete temp_deploy/server/ backend/

            # Instalar dependencias backend y reiniciar servicio con PM2
            cd backend
            npm install --production
            pm2 restart app --silent || pm2 start index.js --name "app"
            cd ..

            # Copiar frontend (Nuxt) a la carpeta temporal
            rsync -av --delete temp_deploy/nuxt/ temp_nuxt/

            # Generar la build de Nuxt
            cd temp_nuxt
            npm install
            npm run build

            # Verificar si "dist" se generó correctamente
            if [ ! -d "dist" ]; then
              echo "Error: La carpeta 'dist' no se generó correctamente"
              exit 1
            fi

            # Reemplazar la carpeta "dist" en frontend
            rsync -av --delete dist/ /var/www/lethalrun/frontend/

            # Recargar Nginx para aplicar los cambios del frontend
            sudo systemctl reload nginx

            # Limpiar archivos temporales
            rm -rf temp_deploy temp_nuxt

            echo "✅ ¡Despliegue completado con éxito!"