name: Deploy to Production

on:
  push:
    branches:
      - TestingGithubActions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout código
        uses: actions/checkout@v3

      # Paso 2: Configurar clave SSH
      - name: Configurar clave SSH
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Paso 3: Conectar y desplegar
      - name: Desplegar a servidor con Docker
        env:
          HOST: ${{ secrets.SERVER_URL }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
            echo "Conectando al servidor y desplegando..."
            
            # Cambiar al directorio del proyecto
            cd /ruta/a/tu/proyecto

            # Detener y eliminar contenedores existentes
            echo "Deteniendo contenedores en ejecución..."
            docker-compose down

            # Actualizar el código desde el repositorio
            echo "Actualizando el código..."
            git pull origin TestingGithubActions

            # Reconstruir e iniciar los contenedores
            echo "Reconstruyendo y reiniciando contenedores..."
            docker-compose up -d --build
          EOF
