name: Deploy to Production

on:
  push:
    branches:
      - TestingGithubActions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Desplegar a servidor
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
            cd /ruta/a/tu/proyecto
            docker stop $(docker ps -aq)
            git pull origin main
            docker-compose -f docker-compose-prod.yml up -d --build
          EOF
